"""baseline: initial schema with all tables

Revision ID: d3eb45a2e046
Revises: 
Create Date: 2026-08-27 10:39:01.210383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3eb45a2e046'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_exit_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=12), nullable=False),
    sa.Column('strategy_execution_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('exited_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('total_realized_pnl', sa.Float(), nullable=False),
    sa.Column('cash_change', sa.Float(), nullable=False),
    sa.Column('positions_json', sa.Text(), nullable=False),
    sa.Column('groups_json', sa.Text(), nullable=False),
    sa.Column('errors_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_order_id', name='uq_bulk_exit_client_order')
    )
    with op.batch_alter_table('bulk_exit_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bulk_exit_records_user_id'), ['user_id'], unique=False)

    op.create_table('contract_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_key', sa.String(length=64), nullable=False),
    sa.Column('underlying', sa.String(length=16), nullable=False),
    sa.Column('underlying_key', sa.String(length=32), nullable=False),
    sa.Column('expiry', sa.String(length=10), nullable=False),
    sa.Column('strike_price', sa.Float(), nullable=False),
    sa.Column('instrument_type', sa.String(length=8), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=True),
    sa.Column('minimum_lot', sa.Integer(), nullable=True),
    sa.Column('freeze_quantity', sa.Integer(), nullable=True),
    sa.Column('tick_size', sa.Float(), nullable=True),
    sa.Column('trading_symbol', sa.String(length=64), nullable=False),
    sa.Column('segment', sa.String(length=16), nullable=False),
    sa.Column('exchange', sa.String(length=8), nullable=False),
    sa.Column('weekly', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_key', name='uq_contract_spec_key')
    )
    with op.batch_alter_table('contract_specs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_specs_expiry'), ['expiry'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_specs_instrument_key'), ['instrument_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_contract_specs_underlying'), ['underlying'], unique=False)

    op.create_table('data_completeness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_key', sa.String(length=64), nullable=False),
    sa.Column('session_date', sa.String(length=10), nullable=False),
    sa.Column('data_type', sa.String(length=32), nullable=False),
    sa.Column('expected_count', sa.Integer(), nullable=True),
    sa.Column('actual_count', sa.Integer(), nullable=False),
    sa.Column('missing_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_verified_at', sa.String(length=32), nullable=True),
    sa.Column('last_attempted_at', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_key', 'session_date', 'data_type', name='uq_data_completeness_identity')
    )
    with op.batch_alter_table('data_completeness', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_completeness_data_type'), ['data_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_completeness_instrument_key'), ['instrument_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_completeness_session_date'), ['session_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_completeness_status'), ['status'], unique=False)

    op.create_table('exit_exposure_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('exit_order_id', sa.Integer(), nullable=False),
    sa.Column('exposure_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exit_exposure_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exit_exposure_allocations_exit_order_id'), ['exit_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exit_exposure_allocations_exposure_id'), ['exposure_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exit_exposure_allocations_user_id'), ['user_id'], unique=False)

    op.create_table('gex_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('expiry', sa.String(length=10), nullable=False),
    sa.Column('spot', sa.Float(), nullable=False),
    sa.Column('methodology', sa.String(length=32), nullable=False),
    sa.Column('sign_convention', sa.String(length=32), nullable=False),
    sa.Column('call_gex', sa.Float(), nullable=True),
    sa.Column('put_gex', sa.Float(), nullable=True),
    sa.Column('net_gex', sa.Float(), nullable=True),
    sa.Column('availability_status', sa.String(length=16), nullable=False),
    sa.Column('valid_strike_count', sa.Integer(), nullable=False),
    sa.Column('total_strike_count', sa.Integer(), nullable=False),
    sa.Column('chain_age_ms', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('strike_data', sa.Text(), nullable=False),
    sa.Column('expiry_data', sa.Text(), nullable=False),
    sa.Column('methodology_metadata', sa.Text(), nullable=False),
    sa.Column('sweep_data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gex_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gex_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gex_snapshots_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gex_snapshots_symbol'), ['symbol'], unique=False)

    op.create_table('historical_gex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_key', sa.String(length=64), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('open_time', sa.DateTime(), nullable=False),
    sa.Column('spot', sa.Float(), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('expiry', sa.String(length=10), nullable=False),
    sa.Column('option_type', sa.String(length=4), nullable=False),
    sa.Column('gamma', sa.Float(), nullable=False),
    sa.Column('open_interest', sa.Float(), nullable=False),
    sa.Column('option_price', sa.Float(), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=True),
    sa.Column('raw_gex', sa.Float(), nullable=False),
    sa.Column('signed_gex', sa.Float(), nullable=False),
    sa.Column('calc_version', sa.String(length=16), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_key', 'interval', 'open_time', 'calc_version', name='uq_historical_gex_identity')
    )
    with op.batch_alter_table('historical_gex', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_gex_instrument_key'), ['instrument_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_gex_open_time'), ['open_time'], unique=False)

    op.create_table('ingestion_checkpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline', sa.String(length=32), nullable=False),
    sa.Column('instrument_key', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('items_total', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.String(length=32), nullable=True),
    sa.Column('completed_at', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline', 'instrument_key', name='uq_ingestion_checkpoint_identity')
    )
    with op.batch_alter_table('ingestion_checkpoint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_checkpoint_instrument_key'), ['instrument_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_checkpoint_pipeline'), ['pipeline'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_checkpoint_status'), ['status'], unique=False)

    op.create_table('ingestion_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('instrument_key', sa.String(length=64), nullable=True),
    sa.Column('expiry_date', sa.String(length=10), nullable=True),
    sa.Column('session_date', sa.String(length=10), nullable=True),
    sa.Column('started_at', sa.String(length=32), nullable=False),
    sa.Column('completed_at', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('api_calls', sa.Integer(), nullable=False),
    sa.Column('rows_fetched', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_skipped', sa.Integer(), nullable=False),
    sa.Column('duplicates', sa.Integer(), nullable=False),
    sa.Column('error_category', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestion_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_log_instrument_key'), ['instrument_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_log_operation'), ['operation'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_log_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_log_session_date'), ['session_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_log_status'), ['status'], unique=False)

    op.create_table('iv_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('expiry', sa.String(length=10), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('option_type', sa.String(length=8), nullable=False),
    sa.Column('iv', sa.Float(), nullable=False),
    sa.Column('spot', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('iv_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iv_observations_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_iv_observations_symbol'), ['symbol'], unique=False)

    op.create_table('nifty_candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('open_time', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'interval', 'open_time', name='uq_candle_identity')
    )
    with op.batch_alter_table('nifty_candles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nifty_candles_open_time'), ['open_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_nifty_candles_symbol'), ['symbol'], unique=False)

    op.create_table('option_candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_key', sa.String(length=64), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('open_time', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('open_interest', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_key', 'interval', 'open_time', name='uq_option_candle_identity')
    )
    with op.batch_alter_table('option_candles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_option_candles_instrument_key'), ['instrument_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_option_candles_open_time'), ['open_time'], unique=False)

    op.create_table('option_greeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_key', sa.String(length=64), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('open_time', sa.DateTime(), nullable=False),
    sa.Column('spot', sa.Float(), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('expiry', sa.String(length=10), nullable=False),
    sa.Column('option_type', sa.String(length=4), nullable=False),
    sa.Column('option_price', sa.Float(), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=True),
    sa.Column('time_to_expiry', sa.Float(), nullable=False),
    sa.Column('risk_free_rate', sa.Float(), nullable=False),
    sa.Column('intrinsic_value', sa.Float(), nullable=False),
    sa.Column('implied_volatility', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('gamma', sa.Float(), nullable=True),
    sa.Column('vega', sa.Float(), nullable=True),
    sa.Column('theta', sa.Float(), nullable=True),
    sa.Column('calc_model', sa.String(length=32), nullable=False),
    sa.Column('calc_version', sa.String(length=16), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_key', 'interval', 'open_time', 'calc_version', name='uq_option_greeks_identity')
    )
    with op.batch_alter_table('option_greeks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_option_greeks_instrument_key'), ['instrument_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_option_greeks_open_time'), ['open_time'], unique=False)

    op.create_table('paper_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('starting_capital', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_accounts_user_id'), ['user_id'], unique=True)

    op.create_table('paper_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.String(length=40), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('expiry', sa.String(length=10), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('option_type', sa.String(length=8), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filled_quantity', sa.Integer(), nullable=False),
    sa.Column('fill_price', sa.Float(), nullable=True),
    sa.Column('price_source', sa.String(length=16), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('rejected_reason', sa.String(length=255), nullable=True),
    sa.Column('journal_leg_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_order_id', name='uq_order_client_order')
    )
    with op.batch_alter_table('paper_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_orders_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_orders_user_id'), ['user_id'], unique=False)

    op.create_table('paper_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('execution_id', sa.String(length=40), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_transactions_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('expiry', sa.String(length=10), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('option_type', sa.String(length=8), nullable=False),
    sa.Column('net_quantity', sa.Integer(), nullable=False),
    sa.Column('average_entry_price', sa.Float(), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('strategy_execution_id', sa.String(length=40), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', 'expiry', 'strike', 'option_type', name='uq_position_instrument')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_strategy_execution_id'), ['strategy_execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_user_id'), ['user_id'], unique=False)

    op.create_table('strategy_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('execution_id', sa.String(length=40), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=True),
    sa.Column('strategy_tag', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('entry_net', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('entry_at', sa.DateTime(), nullable=False),
    sa.Column('exit_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('execution_metadata', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_order_id', name='uq_execution_client_order')
    )
    with op.batch_alter_table('strategy_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_executions_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_executions_user_id'), ['user_id'], unique=False)

    op.create_table('strategy_leg_exposures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('execution_id', sa.String(length=40), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('expiry', sa.String(length=10), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('option_type', sa.String(length=8), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('original_quantity', sa.Integer(), nullable=False),
    sa.Column('remaining_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'order_id', name='uq_exposure_source_order')
    )
    with op.batch_alter_table('strategy_leg_exposures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_leg_exposures_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_leg_exposures_position_id'), ['position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_leg_exposures_user_id'), ['user_id'], unique=False)

    op.create_table('strategy_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_template_user_name')
    )
    with op.batch_alter_table('strategy_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_templates_user_id'), ['user_id'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('strategy_tag', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('entry_net', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('entry_at', sa.DateTime(), nullable=False),
    sa.Column('exit_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('strategy_execution_id', sa.String(length=40), nullable=True),
    sa.Column('client_order_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_strategy_execution_id'), ['strategy_execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('identity_source', sa.String(length=32), nullable=False),
    sa.Column('broker_provider', sa.String(length=32), nullable=True),
    sa.Column('broker_user_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_provider', 'broker_user_id', name='uq_users_broker_identity')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_broker_user_id'), ['broker_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)

    op.create_table('legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('expiration_date', sa.String(length=10), nullable=False),
    sa.Column('strike_price', sa.Float(), nullable=False),
    sa.Column('option_type', sa.String(length=8), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('premium', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('entry_at', sa.DateTime(), nullable=False),
    sa.Column('exit_at', sa.DateTime(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legs_trade_id'), ['trade_id'], unique=False)

    op.create_table('strategy_template_legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('option_type', sa.String(length=8), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('expiry', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('strike_mode', sa.String(length=20), nullable=False),
    sa.Column('strike_offset', sa.Integer(), nullable=True),
    sa.Column('strike_offset_pct', sa.Float(), nullable=True),
    sa.Column('target_delta', sa.Float(), nullable=True),
    sa.Column('expiry_mode', sa.String(length=20), nullable=False),
    sa.Column('expiry_dte_min', sa.Integer(), nullable=True),
    sa.Column('expiry_dte_max', sa.Integer(), nullable=True),
    sa.Column('formula_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['strategy_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy_template_legs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_template_legs_template_id'), ['template_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_session_hash'), ['session_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_session_hash'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_expires_at'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('strategy_template_legs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_template_legs_template_id'))

    op.drop_table('strategy_template_legs')
    with op.batch_alter_table('legs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legs_trade_id'))

    op.drop_table('legs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_broker_user_id'))

    op.drop_table('users')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_user_id'))
        batch_op.drop_index(batch_op.f('ix_trades_strategy_execution_id'))

    op.drop_table('trades')
    with op.batch_alter_table('strategy_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_templates_user_id'))

    op.drop_table('strategy_templates')
    with op.batch_alter_table('strategy_leg_exposures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_leg_exposures_user_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_leg_exposures_position_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_leg_exposures_execution_id'))

    op.drop_table('strategy_leg_exposures')
    with op.batch_alter_table('strategy_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_executions_user_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_executions_execution_id'))

    op.drop_table('strategy_executions')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_user_id'))
        batch_op.drop_index(batch_op.f('ix_positions_strategy_execution_id'))

    op.drop_table('positions')
    with op.batch_alter_table('paper_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_paper_transactions_execution_id'))

    op.drop_table('paper_transactions')
    with op.batch_alter_table('paper_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_paper_orders_execution_id'))

    op.drop_table('paper_orders')
    with op.batch_alter_table('paper_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_accounts_user_id'))

    op.drop_table('paper_accounts')
    with op.batch_alter_table('option_greeks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_option_greeks_open_time'))
        batch_op.drop_index(batch_op.f('ix_option_greeks_instrument_key'))

    op.drop_table('option_greeks')
    with op.batch_alter_table('option_candles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_option_candles_open_time'))
        batch_op.drop_index(batch_op.f('ix_option_candles_instrument_key'))

    op.drop_table('option_candles')
    with op.batch_alter_table('nifty_candles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nifty_candles_symbol'))
        batch_op.drop_index(batch_op.f('ix_nifty_candles_open_time'))

    op.drop_table('nifty_candles')
    with op.batch_alter_table('iv_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iv_observations_symbol'))
        batch_op.drop_index(batch_op.f('ix_iv_observations_observed_at'))

    op.drop_table('iv_observations')
    with op.batch_alter_table('ingestion_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_log_status'))
        batch_op.drop_index(batch_op.f('ix_ingestion_log_session_date'))
        batch_op.drop_index(batch_op.f('ix_ingestion_log_run_id'))
        batch_op.drop_index(batch_op.f('ix_ingestion_log_operation'))
        batch_op.drop_index(batch_op.f('ix_ingestion_log_instrument_key'))

    op.drop_table('ingestion_log')
    with op.batch_alter_table('ingestion_checkpoint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_checkpoint_status'))
        batch_op.drop_index(batch_op.f('ix_ingestion_checkpoint_pipeline'))
        batch_op.drop_index(batch_op.f('ix_ingestion_checkpoint_instrument_key'))

    op.drop_table('ingestion_checkpoint')
    with op.batch_alter_table('historical_gex', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_gex_open_time'))
        batch_op.drop_index(batch_op.f('ix_historical_gex_instrument_key'))

    op.drop_table('historical_gex')
    with op.batch_alter_table('gex_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gex_snapshots_symbol'))
        batch_op.drop_index(batch_op.f('ix_gex_snapshots_owner_id'))
        batch_op.drop_index(batch_op.f('ix_gex_snapshots_captured_at'))

    op.drop_table('gex_snapshots')
    with op.batch_alter_table('exit_exposure_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exit_exposure_allocations_user_id'))
        batch_op.drop_index(batch_op.f('ix_exit_exposure_allocations_exposure_id'))
        batch_op.drop_index(batch_op.f('ix_exit_exposure_allocations_exit_order_id'))

    op.drop_table('exit_exposure_allocations')
    with op.batch_alter_table('data_completeness', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_completeness_status'))
        batch_op.drop_index(batch_op.f('ix_data_completeness_session_date'))
        batch_op.drop_index(batch_op.f('ix_data_completeness_instrument_key'))
        batch_op.drop_index(batch_op.f('ix_data_completeness_data_type'))

    op.drop_table('data_completeness')
    with op.batch_alter_table('contract_specs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_specs_underlying'))
        batch_op.drop_index(batch_op.f('ix_contract_specs_instrument_key'))
        batch_op.drop_index(batch_op.f('ix_contract_specs_expiry'))

    op.drop_table('contract_specs')
    with op.batch_alter_table('bulk_exit_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulk_exit_records_user_id'))

    op.drop_table('bulk_exit_records')
    # ### end Alembic commands ###
