"""Day 38: add trade lifecycle persistence tables

Revision ID: e8f9a0b1c2d3
Revises: 125e1807df8d
Create Date: 2026-09-06 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8f9a0b1c2d3"
down_revision: Union[str, None] = "125e1807df8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trade_lifecycle_events",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("aggregate_type", sa.String(length=32), nullable=False),
        sa.Column("aggregate_id", sa.String(length=40), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("event_version", sa.String(length=16), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("position_sequence", sa.Integer(), nullable=True),
        sa.Column("quantity_delta", sa.Integer(), nullable=True),
        sa.Column("position_identity_user_id", sa.String(length=128), nullable=True),
        sa.Column("position_identity_symbol", sa.String(length=16), nullable=True),
        sa.Column("position_identity_expiry", sa.String(length=10), nullable=True),
        sa.Column("position_identity_strike", sa.Float(), nullable=True),
        sa.Column("position_identity_option_type", sa.String(length=8), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("aggregate_id", "sequence", name="uq_lifecycle_aggregate_sequence"),
        sa.UniqueConstraint(
            "tenant_id",
            "position_identity_user_id",
            "position_identity_symbol",
            "position_identity_expiry",
            "position_identity_strike",
            "position_identity_option_type",
            "position_sequence",
            name="uq_position_sequence",
        ),
    )
    op.create_index("ix_lifecycle_events_aggregate", "trade_lifecycle_events", ["aggregate_id", "sequence"], unique=False)
    op.create_index("ix_lifecycle_events_tenant", "trade_lifecycle_events", ["tenant_id"], unique=False)
    op.create_index("ix_lifecycle_events_position_seq", "trade_lifecycle_events", ["position_sequence"], unique=False)

    op.create_table(
        "position_sequence_anchor",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("expiry", sa.String(length=10), nullable=False),
        sa.Column("strike", sa.Float(), nullable=False),
        sa.Column("option_type", sa.String(length=8), nullable=False),
        sa.Column("last_position_sequence", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "user_id", "symbol", "expiry", "strike", "option_type"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("position_sequence_anchor")
    op.drop_index("ix_lifecycle_events_position_seq", table_name="trade_lifecycle_events")
    op.drop_index("ix_lifecycle_events_tenant", table_name="trade_lifecycle_events")
    op.drop_index("ix_lifecycle_events_aggregate", table_name="trade_lifecycle_events")
    op.drop_table("trade_lifecycle_events")
    # ### end Alembic commands ###
